// 1. 25 Grand Stage & Wedding Decoration Products
export const DECORATION_STAGE_PRODUCTS = [
  {
    no: 1,
    name: 'Customized Wedding Stage Decorations',
    price: 120000,
    priceDisplay: 'From Rs.120,000',
    description: 'Customized Wedding Stage Decorations featuring grand floral arches, bespoke ambient lighting, and couture stage backdrops.',
    image: 'https://flowerbouquet.pk/cdn/shop/files/weddingstage.jpg?v=1716522682&width=533',
    category: 'Floral stages',
    rentalCategory: 'Stage décor',
    material: 'Fresh Imported Flowers, Gilded Metal Truss & Velvet',
    dimensions: '30ft x 14ft Stage Frame',
    availability: 'In stock',
  },
  {
    no: 2,
    name: 'Grand Mehndi Celebration with Vibrant Stage and Floor Decor',
    price: 149999,
    priceDisplay: 'Rs.149,999',
    description: 'Grand Mehndi decor with a colorful stage, ornate floor designs, cozy seating in yellow and red tones, and detailed lighting for a festive atmosphere.',
    image: 'https://flowerbouquet.pk/cdn/shop/files/Grand_Mehndi_Celebration_with_Vibrant_Stage_and_Floor_Decor.jpg?v=1737028367&width=533',
    category: 'Mehndi setups',
    rentalCategory: 'Stage décor',
    material: 'Marigold Garlands, Velvet Bolsters & Floor Rangoli Carpet',
    dimensions: '36ft x 16ft Staging Deck',
    availability: 'In stock',
  },
  {
    no: 3,
    name: 'Affordable Masehri in Lahore',
    price: 35000,
    priceDisplay: 'Rs.35,000',
    description: 'White & Red Roses Masehri bridal room decoration with fresh fragrant roses and hanging petal strands.',
    image: 'https://flowerbouquet.pk/cdn/shop/files/fed56ad4-6ed5-4760-b59d-39c9b666e0da.jpg?v=1721816046&width=533',
    category: 'Luxury weddings',
    rentalCategory: 'Decorative props',
    material: 'Fresh Red & White Roses, Jasmine Threads & Satin Ribbon',
    dimensions: 'Standard King Bed Canopy / Room Suite',
    availability: 'In stock',
  },
  {
    no: 4,
    name: 'Affordable Walima Decoration In Lahore',
    price: 500000,
    priceDisplay: 'Rs.500,000',
    description: 'Walima decoration Lahore with imperial crystal chandeliers, mirrored runway, luxury pastel floral arrangements, and stage backdrop.',
    image: 'https://flowerbouquet.pk/cdn/shop/files/walima_decoration.png?v=1726123619&width=533',
    category: 'Luxury weddings',
    rentalCategory: 'Stage décor',
    material: 'K9 Crystal Chandeliers, Mirrored Glass Runway & Imported Hydrangeas',
    dimensions: '45ft Full Ballroom Stage & Catwalk',
    availability: 'In stock',
  },
  {
    no: 5,
    name: 'Majestic Mehndi Swing Setup with Elegant Drapes',
    price: 84999,
    priceDisplay: 'Rs.84,999',
    description: 'Traditional wooden swing adorned with colorful drapes and surrounded by floral arrangements, vibrant floor cushions, and a decorative umbrella for a Mehndi event.',
    image: 'https://flowerbouquet.pk/cdn/shop/files/Majestic_Mehndi_Swing_Setup_with_Elegant_Drapes.jpg?v=1737027276&width=533',
    category: 'Mehndi setups',
    rentalCategory: 'Arches',
    material: 'Solid Carved Teakwood Swing, Silk Chiffon Drapes & Fresh Florals',
    dimensions: '8ft x 7ft Swing Rig with 12ft Surround',
    availability: 'In stock',
  },
  {
    no: 6,
    name: 'Cultural Event Stage Decorations In Lahore',
    price: 280000,
    priceDisplay: 'Rs.280,000',
    description: 'Cultural Event Stage Decorations In Lahore with authentic Pakistani heritage motifs, vibrant fabric draping, brass urns, and intelligent stage lighting.',
    image: 'https://flowerbouquet.pk/cdn/shop/files/7717ce07c2d4c1c90fec292883f1738b.jpg?v=1721887354&width=533',
    category: 'Floral stages',
    rentalCategory: 'Stage décor',
    material: 'Truck Art Accents, Spun Brass Urns & Multi-Tiered Staging Deck',
    dimensions: '40ft x 18ft Concert & Gala Stage',
    availability: 'In stock',
  },
  {
    no: 7,
    name: 'Enchanting Staircase Decor',
    price: 49999,
    priceDisplay: 'Rs.49,999',
    description: 'A grand staircase adorned with a captivating display of vibrant floral garlands, twinkling lights, and lush greenery, creating a warm and inviting ambiance.',
    image: 'https://flowerbouquet.pk/cdn/shop/files/Enchanting_Staircase_Decor.jpg?v=1735215523&width=533',
    category: 'Entrance décor',
    rentalCategory: 'Lighting',
    material: 'Eucalyptus Foliage, Warm Fairy LED Mesh & Holland Orchids',
    dimensions: 'Up to 35ft Staircase Railing & Spindle Run',
    availability: 'In stock',
  },
  {
    no: 8,
    name: 'Affordable Mehndi Ceremony in Lahore',
    price: 49000,
    priceDisplay: 'Rs.49,000',
    description: 'Affordable Mehndi Ceremony setup with colorful festive backdrop, marigold accents, dholak corner, and traditional low floor seating.',
    image: 'https://flowerbouquet.pk/cdn/shop/files/images_4.jpg?v=1720001562&width=533',
    category: 'Mehndi setups',
    rentalCategory: 'Stage décor',
    material: 'Yellow & Orange Organza, Marigold Garlands & Low Seating Mats',
    dimensions: '16ft x 10ft Intimate Setup',
    availability: 'In stock',
  },
  {
    no: 9,
    name: 'Affordable barat decoration In Lahore',
    price: 300000,
    priceDisplay: 'Rs.300,000',
    description: 'Affordable barat decoration In Lahore with grand bridal stage, royal red and gold velvet themes, carved throne seating, and double floral arches.',
    image: 'https://flowerbouquet.pk/cdn/shop/files/7717ce07c2d4c1c90fec292883f1738b.jpg?v=1721887354&width=533',
    category: 'Luxury weddings',
    rentalCategory: 'Stage décor',
    material: 'Deep Red Velvet, Gold Leaf Carved Throne & Fresh Red Roses',
    dimensions: '38ft Royal Barat Stage Deck',
    availability: 'In stock',
  },
  {
    no: 10,
    name: 'Sehra Bandi Ceremony in Lahore',
    price: 48000,
    priceDisplay: 'Rs.48,000',
    description: 'Sehra Bandi traditional groom ceremony backdrop with handcrafted pearl beads, royal velvet seating, and auspicious floral arrangements.',
    image: 'https://flowerbouquet.pk/cdn/shop/files/coolbluez-sehra-bandi-beads.jpg?v=1721802912&width=533',
    category: 'Luxury weddings',
    rentalCategory: 'Decorative props',
    material: 'Pearl String Beads, Traditional Velvet Throne & Brass Thali Display',
    dimensions: '14ft Groom Ceremony Enclosure',
    availability: 'In stock',
  },
  {
    no: 11,
    name: 'Vibrant Floral Mehndi Stage with Traditional Seating',
    price: 64999,
    priceDisplay: 'Rs.64,999',
    description: 'A colorful Mehndi stage setup with pink, orange, and yellow floral arrangements, metallic lanterns, traditional low seating, and vibrant cushions on an ornate carpet.',
    image: 'https://flowerbouquet.pk/cdn/shop/files/Vibrant_Floral_Mehndi_Stage_with_Traditional_Se.jpg?v=1737027082&width=533',
    category: 'Mehndi setups',
    rentalCategory: 'Stage décor',
    material: 'Moroccan Metal Lanterns, Traditional Diwan Sofa & Saffron Carpeting',
    dimensions: '20ft x 12ft Stage Deck',
    availability: 'In stock',
  },
  {
    no: 12,
    name: 'Outdoor Mehndi Decor with Vibrant Canopy and Seating',
    price: 119999,
    priceDisplay: 'Rs.119,999',
    description: 'Outdoor Mehndi Decor with Vibrant Canopy and Seating featuring colorful tensile canopy, hanging tassels, fairy light net, and garden floor seating.',
    image: 'https://flowerbouquet.pk/cdn/shop/files/309.jpg?v=1737027404&width=533',
    category: 'Outdoor décor',
    rentalCategory: 'Backdrops',
    material: 'Weatherproof Canopy Drapes, Hanging Tassels & Garden Fairy Lights',
    dimensions: '30ft x 30ft Lawn Pavilion Rig',
    availability: 'In stock',
  },
  {
    no: 13,
    name: 'Luxurious Mehndi Stage with Floral Elegance',
    price: 94999,
    priceDisplay: 'Rs.94,999',
    description: 'A luxurious Mehndi stage setup with a white sofa, vibrant cushions, floral canopy, and a backdrop of multicolored drapes.',
    image: 'https://flowerbouquet.pk/cdn/shop/files/Luxurious_Mehndi_Stage_with_Floral_Elegance.jpg?v=1737027701&width=533',
    category: 'Mehndi setups',
    rentalCategory: 'Stage décor',
    material: 'Tufted White Leatherette Sofa, Silk Flower Canopy & Chiffon Panels',
    dimensions: '24ft x 12ft Raised Stage',
    availability: 'In stock',
  },
  {
    no: 14,
    name: 'Traditional Mehndi Backdrop with Marigold Strings',
    price: 44999,
    priceDisplay: 'Rs.44,999',
    description: 'Traditional Mehndi decor with marigold strings, yellow, orange, and red drapes, along with floor seating for a festive ambiance.',
    image: 'https://flowerbouquet.pk/cdn/shop/files/Traditional_Mehndi_Backdrop_with_Marigold_Strings.jpg?v=1737027883&width=533',
    category: 'Mehndi setups',
    rentalCategory: 'Backdrops',
    material: 'Natural Orange & Yellow Marigolds, Gold Zari Borders & Bolster Pillows',
    dimensions: '16ft x 10ft Backdrop Truss',
    availability: 'In stock',
  },
  {
    no: 15,
    name: 'Festive Umbrella-Themed Mehndi Backdrop',
    price: 64999,
    priceDisplay: 'Rs.64,999',
    description: 'Mehndi decor with vibrant umbrellas, colorful drapes, and a sparkling black backdrop, complemented by cozy seating and traditional decor elements.',
    image: 'https://flowerbouquet.pk/cdn/shop/files/Festive_Umbrella-Themed_Mehndi_Backdrop.jpg?v=1737028135&width=533',
    category: 'Mehndi setups',
    rentalCategory: 'Decorative props',
    material: 'Hand-Embroidered Rajasthani Umbrellas, Sequined Black Drape & Brass Lanterns',
    dimensions: '20ft x 10ft Thematic Wall',
    availability: 'In stock',
  },
  {
    no: 16,
    name: 'Elegant Indoor Mehndi Setup with Floral and Marigold Highlights',
    price: 59999,
    priceDisplay: 'Rs.59,999',
    description: 'Indoor Mehndi decor with marigold strings, pastel flowers, pink and yellow drapes, fairy lights, and cozy seating for an elegant setup.',
    image: 'https://flowerbouquet.pk/cdn/shop/files/Elegant_Indoor_Mehndi_Setup_with_Floral_and_Marigold_Highlights.jpg?v=1737028248&width=533',
    category: 'Mehndi setups',
    rentalCategory: 'Stage décor',
    material: 'Pastel Peach Botanicals, Dimmable Warm Spotlights & Low Seating Mattresses',
    dimensions: '18ft x 10ft Stage Setup',
    availability: 'In stock',
  },
  {
    no: 17,
    name: 'Twinkling Mehndi Backdrop with Fairy Lights and Greenery',
    price: 49999,
    priceDisplay: 'Rs.49,999',
    description: 'Mehndi decor with red, yellow, and pink drapes, fairy lights, and lush greenery, creating a vibrant and festive backdrop for celebrations.',
    image: 'https://flowerbouquet.pk/cdn/shop/files/Twinkling_Mehndi_Backdrop_with_Fairy_Lights_and_Greenery.jpg?v=1737028502&width=533',
    category: 'Mehndi setups',
    rentalCategory: 'Lighting',
    material: 'Micro Fairy LED Curtains, Dense Faux Ivy & Sheer Drape Accents',
    dimensions: '18ft x 10ft Light Curtain Wall',
    availability: 'In stock',
  },
  {
    no: 18,
    name: 'Modern Mehndi Backdrop with Circular Floral Design',
    price: 54999,
    priceDisplay: 'Rs.54,999',
    description: 'Mehndi decor with a circular floral frame, yellow and white flowers, colorful drapes, fairy lights, and a modern blue sofa with vibrant cushions.',
    image: 'https://flowerbouquet.pk/cdn/shop/files/Modern_Mehndi_Backdrop_with_Circular_Floral_Design.jpg?v=1737028867&width=533',
    category: 'Mehndi setups',
    rentalCategory: 'Arches',
    material: '8ft Gold Halo Ring Arch, White Roses & Modern Royal Blue Velvet Sofa',
    dimensions: '8ft Ring Frame with 16ft Wide Backdrop',
    availability: 'In stock',
  },
  {
    no: 19,
    name: 'Outdoor Floral Mehndi Swing Setup',
    price: 44999,
    priceDisplay: 'Rs.44,999',
    description: 'Outdoor Mehndi decor with a white swing, pink, red, and orange floral arrangements, marigold strings, and traditional props for a festive ambiance.',
    image: 'https://flowerbouquet.pk/cdn/shop/files/Outdoor_Floral_Mehndi_Swing_Setup.jpg?v=1737028997&width=533',
    category: 'Outdoor décor',
    rentalCategory: 'Decorative props',
    material: 'High-Gloss White Iron Swing, Exotic Fresh Floral Garlands & Brass Urns',
    dimensions: '7ft x 6ft Swing Stand Rig',
    availability: 'In stock',
  },
  {
    no: 20,
    name: 'Rustic Mehndi Corner with Floral Arch and Tassels',
    price: 59999,
    priceDisplay: 'Rs.59,999',
    description: 'Mehndi corner decor with a floral arch, tassels, a rustic sofa with colorful cushions, and lanterns for a cozy and festive look.',
    image: 'https://flowerbouquet.pk/cdn/shop/files/Rustic_Mehndi_Corner_with_Floral_Arch_and_Tassels.jpg?v=1737029091&width=533',
    category: 'Mehndi setups',
    rentalCategory: 'Arches',
    material: 'Timber Branch Archway, Silk Tassels & Rustic Jute Upholstered Sofa',
    dimensions: '14ft x 10ft Photo Corner',
    availability: 'In stock',
  },
  {
    no: 21,
    name: 'Luxurious Indoor Mehndi Setup with Red Floral Arch',
    price: 79999,
    priceDisplay: 'Rs.79,999',
    description: 'Indoor Mehndi decor with a red floral arch, fairy lights, a red carpet, and traditional cushions for a luxurious and festive setup.',
    image: 'https://flowerbouquet.pk/cdn/shop/files/Luxurious_Indoor_Mehndi_Setup_with_Red_Floral_Arch.jpg?v=1737029310&width=533',
    category: 'Mehndi setups',
    rentalCategory: 'Arches',
    material: 'Crimson Dutch Roses, Red Velvet Aisle Carpet & Warm Spotlights',
    dimensions: '22ft x 12ft Staging Suite',
    availability: 'In stock',
  },
  {
    no: 22,
    name: 'Elegant Outdoor Mehndi Pavilion with Floor Seating',
    price: 149999,
    priceDisplay: 'Rs.149,999',
    description: 'Outdoor Mehndi pavilion with yellow and orange drapes, floral accents, cozy floor seating, and traditional low tables for a grand celebration.',
    image: 'https://flowerbouquet.pk/cdn/shop/files/Elegant_Outdoor_Mehndi_Pavilion_with_Floor_Seating.jpg?v=1737029691&width=533',
    category: 'Outdoor décor',
    rentalCategory: 'Stage décor',
    material: 'Steel Pavilion Truss, Marigold Chandeliers & Low Wooden Chowkis',
    dimensions: '35ft x 25ft Outdoor Enclosure',
    availability: 'In stock',
  },
  {
    no: 23,
    name: 'Minimalist Mehndi Backdrop with Umbrella Decorations',
    price: 49999,
    priceDisplay: 'Rs.49,999',
    description: 'Minimalist Mehndi backdrop with green drapes, colorful umbrellas, decorative lanterns, and a gold bench for an intimate and charming setup.',
    image: 'https://flowerbouquet.pk/cdn/shop/files/Minimalist_Mehndi_Backdrop_with_Umbrella_Decorations.jpg?v=1737029802&width=533',
    category: 'Mehndi setups',
    rentalCategory: 'Backdrops',
    material: 'Emerald Green Drape, Miniature Embroidered Umbrellas & Gilded Bench',
    dimensions: '15ft x 9ft Intimate Wall',
    availability: 'In stock',
  },
  {
    no: 24,
    name: 'Majestic Mehndi Stage with Vibrant Drapes and Floral Arrangements',
    price: 119999,
    priceDisplay: 'Rs.119,999',
    description: 'Mehndi stage with vibrant pink, orange, and yellow drapes, a traditional wooden swing, lush floral arrangements, and colorful floor decor for a regal celebration.',
    image: 'https://flowerbouquet.pk/cdn/shop/files/Majestic_Mehndi_Stage_with_Vibrant_Drapes_and_Floral_Arrangements.jpg?v=1737029950&width=533',
    category: 'Mehndi setups',
    rentalCategory: 'Stage décor',
    material: 'Tri-Tone Silk Draping, Floral Arch Overhead & Velvet Floor Risers',
    dimensions: '28ft x 14ft Grand Stage',
    availability: 'In stock',
  },
  {
    no: 25,
    name: 'Fairy Light Mehndi Backdrop with Floral Elegance',
    price: 54999,
    priceDisplay: 'Rs.54,999',
    description: 'Mehndi backdrop with multicolored drapes, fairy lights, floral arrangements, and decorative umbrellas for an elegant and festive setup.',
    image: 'https://flowerbouquet.pk/cdn/shop/files/Fairy_Light_Mehndi_Backdrop_with_Floral_Elegance.jpg?v=1737030041&width=533',
    category: 'Mehndi setups',
    rentalCategory: 'Lighting',
    material: 'Warm Twinkle Curtain Lights, Multicolor Organza Drapes & Fresh Rose Garlands',
    dimensions: '18ft x 10ft Stage Backdrop',
    availability: 'In stock',
  },
];

// 2. 100 Real E-Commerce & Floral Products from flowerbouquet.pk CSV
export const RAW_100_PRODUCTS = [
  { no: 1, name: 'Elegant Black Wrapped Rose Bouquet', category: 'Flower Bouquets', price: 2999, status: 'In stock', image: 'https://flowerbouquet.pk/cdn/shop/files/Elegant_Black_Wrapped_Rose_Bouquet.png', link: 'https://flowerbouquet.pk/products/elegant-black-wrapped-rose-bouquet' },
  { no: 2, name: 'Sorry Flower Bouquet', category: 'Flower Bouquets', price: 1999, status: 'In stock', image: 'https://flowerbouquet.pk/cdn/shop/files/sorry_Rose_Bouquet_with_black_wrapped.png', link: 'https://flowerbouquet.pk/products/sorry-flower-bouquet' },
  { no: 3, name: 'Vibrant Rose Bouquet', category: 'Flower Bouquets', price: 3499, status: 'In stock', image: 'https://flowerbouquet.pk/cdn/shop/files/458.png', link: 'https://flowerbouquet.pk/products/vibrant-rose-bouquet' },
  { no: 4, name: 'Elegant Purple Rose Bouquet', category: 'Flower Bouquets', price: 10999, status: 'In stock', image: 'https://flowerbouquet.pk/cdn/shop/files/461_0d2c2de5-ed85-4051-aeaa-afb377cfc162.png', link: 'https://flowerbouquet.pk/products/elegant-purple-rose-bouquet' },
  { no: 5, name: 'Elegant Floral Jewelry Set', category: 'Flower Bouquets', price: 6999, status: 'In stock', image: 'https://flowerbouquet.pk/cdn/shop/files/FL0WERSBOUQUET_InstagramPost_5.png', link: 'https://flowerbouquet.pk/products/elegant-floral-jewelry-set' },
  { no: 6, name: 'Delicate Pink Rose Bouquet', category: 'Flower Bouquets', price: 2999, status: 'In stock', image: 'https://flowerbouquet.pk/cdn/shop/files/flower_bouquet_trio.png', link: 'https://flowerbouquet.pk/products/delicate-pink-rose-bouquet' },
  { no: 7, name: 'Crimson Rose Bouquet', category: 'Flower Bouquets', price: 12999, status: 'In stock', image: 'https://flowerbouquet.pk/cdn/shop/files/463_2b674f5f-39fc-4095-9210-6d02c0bc2d40.png', link: 'https://flowerbouquet.pk/products/crimson-rose-bouquet' },
  { no: 8, name: 'Vibrant Floral Bouquet', category: 'Flower Bouquets', price: 4499, status: 'In stock', image: 'https://flowerbouquet.pk/cdn/shop/files/462_0196adc8-32f9-46a9-a7ba-ebfa0bf530e6.png', link: 'https://flowerbouquet.pk/products/vibrant-floral-bouquet' },
  { no: 9, name: 'Red and White Floral Bouquet', category: 'Flower Bouquets', price: 4999, status: 'In stock', image: 'https://flowerbouquet.pk/cdn/shop/files/red-and-white-floral-bouquet.png', link: 'https://flowerbouquet.pk/products/red-and-white-floral-bouquet' },
  { no: 10, name: 'Elegant White Rose Bouquet', category: 'Flower Bouquets', price: 3999, status: 'In stock', image: 'https://flowerbouquet.pk/cdn/shop/files/464_199d099c-3e83-458e-8be3-78670bb017fe.png', link: 'https://flowerbouquet.pk/products/elegant-white-rose-bouquet-1' },
  { no: 11, name: 'Elegant Paste Bouquet', category: 'Flower Bouquets', price: 6499, status: 'In stock', image: 'https://flowerbouquet.pk/cdn/shop/files/15.png', link: 'https://flowerbouquet.pk/products/elegant-paste-bouquet' },
  { no: 12, name: 'Eternal Elegance', category: 'Flower Bouquets', price: 1399, status: 'In stock', image: 'https://flowerbouquet.pk/cdn/shop/files/solo_flowers_bouquet_with_black_wrap.png', link: 'https://flowerbouquet.pk/products/eternal-elegance' },
  { no: 13, name: 'Single Rose Delight', category: 'Flower Bouquets', price: 2299, status: 'In stock', image: 'https://flowerbouquet.pk/cdn/shop/files/20.png', link: 'https://flowerbouquet.pk/products/single-rose-delight' },
  { no: 14, name: 'Single Red Rose Bouquet', category: 'Flower Bouquets', price: 1499, status: 'In stock', image: 'https://flowerbouquet.pk/cdn/shop/files/6_39acbb0f-1360-4774-afb2-4f1fb4e55a31.png', link: 'https://flowerbouquet.pk/products/single-red-rose-bouquet' },
  { no: 15, name: 'Affordable Rose Bouquet', category: 'Flower Bouquets', price: 2499, status: 'In stock', image: 'https://flowerbouquet.pk/cdn/shop/files/handied_flower_bouquet.png', link: 'https://flowerbouquet.pk/products/affordable-rose-bouquet-1' },
  { no: 16, name: 'Small Imported Single Rose Bouquet', category: 'Flower Bouquets', price: 1499, status: 'Out of stock', image: 'https://flowerbouquet.pk/cdn/shop/files/single_pink_rose_bouquet.png', link: 'https://flowerbouquet.pk/products/small-imported-single-rose-bouquet' },
  { no: 17, name: 'Budgeted Imported Flower Bouquet', category: 'Flower Bouquets', price: 6999, status: 'In stock', image: 'https://flowerbouquet.pk/cdn/shop/files/483_04511eaa-fc7a-4d62-beaf-9a4ec3980628.png', link: 'https://flowerbouquet.pk/products/flower-bouquet-under-5000' },
  { no: 18, name: "Father's Day Flower Mug", category: 'Flower Bouquets', price: 5999, status: 'Out of stock', image: 'https://flowerbouquet.pk/cdn/shop/files/FL0WERSBOUQUET_InstagramPost_6.png', link: 'https://flowerbouquet.pk/products/fathers-day-flower-mug' },
  { no: 19, name: 'Red Rose Gajra', category: 'Flower Bouquets', price: 370, status: 'Out of stock', image: 'https://flowerbouquet.pk/cdn/shop/files/482_13cd4693-0a0d-48a5-bc78-498d0a6df523.png', link: 'https://flowerbouquet.pk/products/red-rose-gajra-in-lahore' },
  { no: 20, name: 'Single Imported Flower', category: 'Flower Bouquets', price: 1499, status: 'Out of stock', image: 'https://flowerbouquet.pk/cdn/shop/files/FL0WERSBOUQUET_InstagramPost_3.png', link: 'https://flowerbouquet.pk/products/single-imported-flower' },
  { no: 21, name: 'Wishes for Mom', category: 'Flower Bouquets', price: 7999, status: 'Out of stock', image: 'https://flowerbouquet.pk/cdn/shop/files/FL0WERSBOUQUET_InstagramPost_7.png', link: 'https://flowerbouquet.pk/products/wishes-for-mom' },
  { no: 22, name: 'Lively Springtime', category: 'Flower Bouquets', price: 10999, status: 'In stock', image: 'https://flowerbouquet.pk/cdn/shop/files/FL0WERSBOUQUET_InstagramPost_8.png', link: 'https://flowerbouquet.pk/products/lively-springtime' },
  { no: 23, name: 'Mum Bouquet', category: 'Flower Bouquets', price: 5999, status: 'Out of stock', image: 'https://flowerbouquet.pk/cdn/shop/files/FL0WERSBOUQUET_InstagramPost_9.png', link: 'https://flowerbouquet.pk/products/mum-bouquet' },
  { no: 24, name: 'Radiant Pink Shine', category: 'Flower Bouquets', price: 7999, status: 'Out of stock', image: 'https://flowerbouquet.pk/cdn/shop/files/FL0WERSBOUQUET_InstagramPost_10.png', link: 'https://flowerbouquet.pk/products/radiant-pink-shine' },
  { no: 25, name: 'Blossom Vibes Flower Bouquet', category: 'Flower Bouquets', price: 6999, status: 'Out of stock', image: 'https://flowerbouquet.pk/cdn/shop/files/FL0WERSBOUQUET_InstagramPost_11.png', link: 'https://flowerbouquet.pk/products/blossom-vibes-flower-bouquet' },
  { no: 26, name: 'Pink Splash', category: 'Flower Bouquets', price: 5999, status: 'Out of stock', image: 'https://flowerbouquet.pk/cdn/shop/files/FL0WERSBOUQUET_InstagramPost_12.png', link: 'https://flowerbouquet.pk/products/color-splash-bouquet' },
  { no: 27, name: 'Bloom Wish', category: 'Flower Bouquets', price: 9499, status: 'Out of stock', image: 'https://flowerbouquet.pk/cdn/shop/files/FL0WERSBOUQUET_InstagramPost_13.png', link: 'https://flowerbouquet.pk/products/bloom-wish-flower-bouquet' },
  { no: 28, name: 'Majestic Mix Flower Bouquet', category: 'Flower Bouquets', price: 13499, status: 'Out of stock', image: 'https://flowerbouquet.pk/cdn/shop/files/469.png', link: 'https://flowerbouquet.pk/products/majestic-mix-flower-bouquet' },
  { no: 29, name: 'Forever & Always Flower Bouquet', category: 'Flower Bouquets', price: 14999, status: 'Out of stock', image: 'https://flowerbouquet.pk/cdn/shop/files/485_6f98a00a-a881-41de-a9a1-a4b0ace11c58.png', link: 'https://flowerbouquet.pk/products/forever-always-flower-bouquet' },
  { no: 30, name: 'Kisses and Hugs Flower Bouquet', category: 'Flower Bouquets', price: 14999, status: 'Out of stock', image: 'https://flowerbouquet.pk/cdn/shop/files/FL0WERSBOUQUET_InstagramPost_14.png', link: 'https://flowerbouquet.pk/products/kisses-and-hugs-flower-bouquet' },
  { no: 31, name: 'Perfect Proposal Flower Bouquet', category: 'Flower Bouquets', price: 8499, status: 'Out of stock', image: 'https://flowerbouquet.pk/cdn/shop/files/Perfect_Proposal.png', link: 'https://flowerbouquet.pk/products/perfect-proposal-flower-bouquet' },
  { no: 32, name: 'Lovely Delight Flower Bouquet', category: 'Flower Bouquets', price: 12499, status: 'Out of stock', image: 'https://flowerbouquet.pk/cdn/shop/files/473_27e2a283-36b2-4939-8b27-321a80e02284.png', link: 'https://flowerbouquet.pk/products/lovely-delight-flower-bouquet' },
  { no: 33, name: 'Pure Love Flower Bouquet', category: 'Flower Bouquets', price: 19999, status: 'Out of stock', image: 'https://flowerbouquet.pk/cdn/shop/files/474.png', link: 'https://flowerbouquet.pk/products/pure-love-flower-bouquet' },
  { no: 34, name: 'Snowy Delight Flower Bouquet', category: 'Flower Bouquets', price: 21999, status: 'Out of stock', image: 'https://flowerbouquet.pk/cdn/shop/files/487_321688c9-0798-4a45-896d-632d49813064.png', link: 'https://flowerbouquet.pk/products/snowy-delight-flower-bouquet' },
  { no: 35, name: 'Blushing Beauty Flower Bouquet', category: 'Flower Bouquets', price: 9999, status: 'Out of stock', image: 'https://flowerbouquet.pk/cdn/shop/files/3_ec260f4d-4a1c-4474-84ad-c07122eee70e.jpg', link: 'https://flowerbouquet.pk/products/blushing-beauty-flower-bouquet' },
  { no: 36, name: 'Sweet Flower Bouquet', category: 'Flower Bouquets', price: 12999, status: 'Out of stock', image: 'https://flowerbouquet.pk/cdn/shop/files/sweet_white_flowers.png', link: 'https://flowerbouquet.pk/products/sweet-tranquility-flower-bouquet' },
  { no: 37, name: 'Summer Splendor Flower Bouquet', category: 'Flower Bouquets', price: 8999, status: 'In stock', image: 'https://flowerbouquet.pk/cdn/shop/files/488_eab3569c-370b-4154-ac1e-f75e60994aca.png', link: 'https://flowerbouquet.pk/products/summer-splendor-flower-bouquet' },
  { no: 38, name: 'Chrysanthemum Charm Flower Bouquet', category: 'Flower Bouquets', price: 8499, status: 'In stock', image: 'https://flowerbouquet.pk/cdn/shop/files/475.png', link: 'https://flowerbouquet.pk/products/chrysanthemum-charm-flower-bouquet' },
  { no: 39, name: 'Heartfelt Moments Flower Bouquet', category: 'Flower Bouquets', price: 7499, status: 'Out of stock', image: 'https://flowerbouquet.pk/cdn/shop/files/465.png', link: 'https://flowerbouquet.pk/products/heartfelt-moments-flower-bouquet' },
  { no: 40, name: 'Floral Dreams Flower Bouquet', category: 'Flower Bouquets', price: 9499, status: 'Out of stock', image: 'https://flowerbouquet.pk/cdn/shop/files/466.png', link: 'https://flowerbouquet.pk/products/floral-dreams-flower-bouquet' },
  { no: 41, name: 'Simply Something Flower Bouquet', category: 'Flower Bouquets', price: 4349, status: 'In stock', image: 'https://flowerbouquet.pk/cdn/shop/files/490.png', link: 'https://flowerbouquet.pk/products/simply-something-flower-bouquet' },
  { no: 42, name: 'Floral Flamingo Flower Bouquet', category: 'Flower Bouquets', price: 24999, status: 'Out of stock', image: 'https://flowerbouquet.pk/cdn/shop/files/477.png', link: 'https://flowerbouquet.pk/products/floral-flamingo-flower-bouquet' },
  { no: 43, name: 'Evening Gala Flower Bouquet', category: 'Flower Bouquets', price: 11999, status: 'Out of stock', image: 'https://flowerbouquet.pk/cdn/shop/files/479.png', link: 'https://flowerbouquet.pk/products/evening-gala-flower-bouquet' },
  { no: 44, name: 'Golden Glow Flower Bouquet', category: 'Flower Bouquets', price: 20999, status: 'Out of stock', image: 'https://flowerbouquet.pk/cdn/shop/files/478.png', link: 'https://flowerbouquet.pk/products/golden-glow-flower-bouquet' },
  { no: 45, name: 'Cool Cobalt Flower Bouquet', category: 'Flower Bouquets', price: 12999, status: 'Out of stock', image: 'https://flowerbouquet.pk/cdn/shop/files/483.png', link: 'https://flowerbouquet.pk/products/cool-cobalt-flower-bouquet' },
  { no: 46, name: "Nature's Bounty Flower Bouquet", category: 'Flower Bouquets', price: 6250, status: 'Out of stock', image: 'https://flowerbouquet.pk/cdn/shop/files/482.png', link: 'https://flowerbouquet.pk/products/natures-bounty-flower-bouquet' },
  { no: 47, name: 'Fairy Floss 100 Flower Bouquet', category: 'Flower Bouquets', price: 69999, status: 'Out of stock', image: 'https://flowerbouquet.pk/cdn/shop/files/485.png', link: 'https://flowerbouquet.pk/products/fairy-floss-flower-bouquet' },
  { no: 48, name: 'Roaming Petals Flower Bouquet', category: 'Flower Bouquets', price: 7849, status: 'In stock', image: 'https://flowerbouquet.pk/cdn/shop/files/476.png', link: 'https://flowerbouquet.pk/products/roaming-petals-flower-bouquet' },
  { no: 49, name: 'Floral Grace Flower Bouquet', category: 'Flower Bouquets', price: 6999, status: 'Out of stock', image: 'https://flowerbouquet.pk/cdn/shop/files/481.png', link: 'https://flowerbouquet.pk/products/floral-grace-flower-bouquet' },
  { no: 50, name: 'Crimson Enchantment Flower Bouquet', category: 'Flower Bouquets', price: 11999, status: 'Out of stock', image: 'https://flowerbouquet.pk/cdn/shop/files/490_86b5d0ac-395d-4628-934f-e6e04dc25927.png', link: 'https://flowerbouquet.pk/products/crimson-enchantment-flower-bouquet' },
  { no: 51, name: 'Eid Glow Flower Bouquet', category: 'Flower Bouquets', price: 6499, status: 'Out of stock', image: 'https://flowerbouquet.pk/cdn/shop/files/494.png', link: 'https://flowerbouquet.pk/products/eid-glow-flower-bouquet' },
  { no: 52, name: "Mom's Embrace Flower Bouquet", category: 'Flower Bouquets', price: 6999, status: 'Out of stock', image: 'https://flowerbouquet.pk/cdn/shop/files/493_d0feec94-c46f-4d19-b7ce-c8c8eb614d42.png', link: 'https://flowerbouquet.pk/products/moms-embrace-flower-bouquet' },
  { no: 53, name: 'Sunshine Bouquet', category: 'Flower Bouquets', price: 7499, status: 'In stock', image: 'https://flowerbouquet.pk/cdn/shop/files/495.png', link: 'https://flowerbouquet.pk/products/sunshine-bouquet' },
  { no: 54, name: "Mom's Delight Bouquet", category: 'Flower Bouquets', price: 16999, status: 'Out of stock', image: 'https://flowerbouquet.pk/cdn/shop/files/496.png', link: 'https://flowerbouquet.pk/products/moms-delight-bouquet' },
  { no: 55, name: "Mom's Love Bouquet", category: 'Flower Bouquets', price: 6999, status: 'Out of stock', image: 'https://flowerbouquet.pk/cdn/shop/files/497.png', link: 'https://flowerbouquet.pk/products/moms-love-bouquet' },
  { no: 56, name: 'Blush Rose Elegance', category: 'Flower Bouquets', price: 4700, status: 'Out of stock', image: 'https://flowerbouquet.pk/cdn/shop/files/498.png', link: 'https://flowerbouquet.pk/products/blush-rose-elegance' },
  { no: 57, name: '100 Roses Bouquet', category: 'Flower Bouquets', price: 12999, status: 'In stock', image: 'https://flowerbouquet.pk/cdn/shop/files/100-flowers-bouquet.png', link: 'https://flowerbouquet.pk/products/100-flowers-bouquet' },
  { no: 58, name: '500 Roses Bouquet', category: 'Flower Bouquets', price: 34999, status: 'In stock', image: 'https://flowerbouquet.pk/cdn/shop/files/4.png', link: 'https://flowerbouquet.pk/products/500-roses-bouquet-delivery' },
  { no: 59, name: 'Red Rose Bouquet – Black Wrap', category: 'Flower Bouquets', price: 1999, status: 'In stock', image: 'https://flowerbouquet.pk/cdn/shop/files/Red_rose_bouquets.png', link: 'https://flowerbouquet.pk/products/red-rose-bouquet-black-wrap' },
  { no: 60, name: 'Sunflower Bouquet – Kraft Wrap', category: 'Flower Bouquets', price: 6499, status: 'In stock', image: 'https://flowerbouquet.pk/cdn/shop/files/sunflower_bouquet.png', link: 'https://flowerbouquet.pk/products/sunflower-bouquet-online' },
  { no: 61, name: 'Sunflower & White Roses – Black Wrap', category: 'Flower Bouquets', price: 2499, status: 'In stock', image: 'https://flowerbouquet.pk/cdn/shop/files/Flower_Bouquet_Listings_1.png', link: 'https://flowerbouquet.pk/products/sunflower-white-roses-black-bouquet' },
  { no: 62, name: 'Romantic Mixed Roses – Black Wrap', category: 'Flower Bouquets', price: 8499, status: 'In stock', image: 'https://flowerbouquet.pk/cdn/shop/files/imported_mixed_roses_bouquet.png', link: 'https://flowerbouquet.pk/products/imported-roses-black-wrap' },
  { no: 63, name: 'Imported Rose Duo Collection', category: 'Flower Bouquets', price: 2500, status: 'In stock', image: 'https://flowerbouquet.pk/cdn/shop/files/flowers_dou_bouquet.png', link: 'https://flowerbouquet.pk/products/imported-rose-duo-collection' },
  { no: 64, name: 'Layers Raffaello Cake', category: 'Cakes & Chocolates', price: 3499, status: 'Out of stock', image: 'https://flowerbouquet.pk/cdn/shop/files/rafaelo-q0b9wbsor4rh60mbm77w8z0fdtxwv8vtqpcq67vqtk.jpg', link: 'https://flowerbouquet.pk/products/raffaello-cake' },
  { no: 65, name: 'Layers Lotus three Milk Cake', category: 'Cakes & Chocolates', price: 3799, status: 'Out of stock', image: 'https://flowerbouquet.pk/cdn/shop/files/Lotus-Three-Milk-Cake_73020f22-aebe-419e-9698-037791030b7e.jpg', link: 'https://flowerbouquet.pk/products/layers-lotus-three-milk-cake' },
  { no: 66, name: 'Layers Ferrero Classic Cake', category: 'Cakes & Chocolates', price: 2999, status: 'Out of stock', image: 'https://flowerbouquet.pk/cdn/shop/files/Ferrero-Classic-pgtfyrzbln55w2y8b11utotx6i73raxrnm9fhhngjs.jpg', link: 'https://flowerbouquet.pk/products/ferrero-classic-cake' },
  { no: 67, name: 'Layers Milky Malt Cake', category: 'Cakes & Chocolates', price: 2399, status: 'Out of stock', image: 'https://flowerbouquet.pk/cdn/shop/files/Milky-Malt-pgtfz5529bn6emf466qmslidhwe8r2e0dfe87d3y4o.jpg', link: 'https://flowerbouquet.pk/products/milky-malt-cake' },
  { no: 68, name: 'Layers Chocolate Heaven Cake', category: 'Cakes & Chocolates', price: 2699, status: 'Out of stock', image: 'https://flowerbouquet.pk/cdn/shop/files/Chocolate-Heaven-pgtfyrzbln55w2y8b11utotx6i73raxrnm9fhhngjs.jpg', link: 'https://flowerbouquet.pk/products/chocolate-heaven-cake' },
  { no: 69, name: 'Layers Lotus Cake', category: 'Cakes & Chocolates', price: 3499, status: 'Out of stock', image: 'https://flowerbouquet.pk/cdn/shop/files/Lotus-pgtfyzi14bfggynb34avdmxlxl61gvrmcnhbbpcb60.jpg', link: 'https://flowerbouquet.pk/products/lotus-cake' },
  { no: 70, name: 'Ferrero Rocher Pack Gift', category: 'Cakes & Chocolates', price: 1499, status: 'In stock', image: 'https://flowerbouquet.pk/cdn/shop/files/ferrero-rocher-16-pack-perfect-gift.png', link: 'https://flowerbouquet.pk/products/ferrero-rocher-16-pack-perfect-gift-for-birthdays-anniversaries-imported-luxury-chocolates' },
  { no: 71, name: 'Nestle KitKat 4 Finger Bar Gift', category: 'Cakes & Chocolates', price: 410, status: 'Out of stock', image: 'https://flowerbouquet.pk/cdn/shop/files/Nestle_KitKat-4_Finger.png', link: 'https://flowerbouquet.pk/products/buy-nestle-kitkat-4-finger-bar-online' },
  { no: 72, name: 'Bounty Chocolate Bar 57g Gift', category: 'Cakes & Chocolates', price: 350, status: 'Out of stock', image: 'https://flowerbouquet.pk/cdn/shop/files/bounty_chocolate_57g.png', link: 'https://flowerbouquet.pk/products/order-bounty-chocolate-bar-57g-online-for-fast-delivery-in-lahore' },
  { no: 73, name: 'Snickers Chocolate 57Gm', category: 'Cakes & Chocolates', price: 394, status: 'Out of stock', image: 'https://flowerbouquet.pk/cdn/shop/files/snickers-chocolaate_900x_b39d3bcc-d529-42f0-884c-79fdd9abacb9.webp', link: 'https://flowerbouquet.pk/products/snickers-chocolate-bar' },
  { no: 74, name: 'Mars Chocolate 51Gm', category: 'Cakes & Chocolates', price: 378, status: 'Out of stock', image: 'https://flowerbouquet.pk/cdn/shop/files/Mars_chocolate_bar.png', link: 'https://flowerbouquet.pk/products/mars-chocolate-bar' },
  { no: 75, name: 'Twix Chocolate 50Gm', category: 'Cakes & Chocolates', price: 399, status: 'Out of stock', image: 'https://flowerbouquet.pk/cdn/shop/files/Twix_chocolate.png', link: 'https://flowerbouquet.pk/products/twix-chocolate-50gm' },
  { no: 76, name: 'Mars Miniatures 220G', category: 'Cakes & Chocolates', price: 2144, status: 'Out of stock', image: 'https://flowerbouquet.pk/cdn/shop/files/Mars_Miniatures_220G.webp', link: 'https://flowerbouquet.pk/products/mars-miniatures-chocolate-pack' },
  { no: 77, name: 'Snickers Miniatures 220G', category: 'Cakes & Chocolates', price: 2144, status: 'Out of stock', image: 'https://flowerbouquet.pk/cdn/shop/files/Snickers_Miniatures_chocolate_pouch_with_individually_wrapped_bars.webp', link: 'https://flowerbouquet.pk/products/snickers-miniatures-chocolate' },
  { no: 78, name: 'Snickers Minis Pouch 180G', category: 'Cakes & Chocolates', price: 2798, status: 'Out of stock', image: 'https://flowerbouquet.pk/cdn/shop/files/Snickers_Minis_Pouch_180G.webp', link: 'https://flowerbouquet.pk/products/snickers-minis-12-pack' },
  { no: 79, name: 'Mr. Beast Feastables Milk Crunch Chocolate (10 x 60g)', category: 'Cakes & Chocolates', price: 2300, status: 'Out of stock', image: 'https://flowerbouquet.pk/cdn/shop/files/MrBeast_Feastables_milk_chocolate.png', link: 'https://flowerbouquet.pk/products/mrbeast-feastables-milk-chocolate' },
  { no: 80, name: 'Layers Dairy Milk Cake', category: 'Cakes & Chocolates', price: 2699, status: 'Out of stock', image: 'https://flowerbouquet.pk/cdn/shop/files/Dairy-Milk-pgtfyvqoczab6isrp2od3nvrk1okm3cp04vdelhvuw.jpg', link: 'https://flowerbouquet.pk/products/dairy-milk-cake' },
  { no: 81, name: 'Layers Pistachio Cake', category: 'Cakes & Chocolates', price: 3899, status: 'Out of stock', image: 'https://flowerbouquet.pk/cdn/shop/files/Pistachio-qjdpxbw0zp9y3n1ppyklw6lcs63x8o8jl8pd205sp4.jpg', link: 'https://flowerbouquet.pk/products/pistachio-cake' },
  { no: 82, name: 'Layers Belgian Malt Cake', category: 'Cakes & Chocolates', price: 3099, status: 'Out of stock', image: 'https://flowerbouquet.pk/cdn/shop/files/Belgian-Chocolate-pgtfyq3n7z2l8v0ym08lopazzqgdbwqazcygixq8w8.jpg', link: 'https://flowerbouquet.pk/products/belgian-malt-cake' },
  { no: 83, name: 'Layers Ferrero Rocher Cake', category: 'Cakes & Chocolates', price: 3999, status: 'Out of stock', image: 'https://flowerbouquet.pk/cdn/shop/files/ferrero-square-ptftrhoqbeg2qiuvjgh536xtsy42tljwwjbbx0choo.jpg', link: 'https://flowerbouquet.pk/products/ferrero-rocher-cake' },
  { no: 84, name: 'Layers Nutella Cake', category: 'Cakes & Chocolates', price: 2799, status: 'Out of stock', image: 'https://flowerbouquet.pk/cdn/shop/files/Nutella-pgtfyvqoczab6isrp2od3nvrk1okm3cp04vdelhvuw.jpg', link: 'https://flowerbouquet.pk/products/nutella-cake' },
  { no: 85, name: 'Layers Red Velvet Cake', category: 'Cakes & Chocolates', price: 2799, status: 'Out of stock', image: 'https://flowerbouquet.pk/cdn/shop/files/Red-Velvet-pgtfyyk6xhe65coo8lw8t565c7ao96nw0ittufdpc8.jpg', link: 'https://flowerbouquet.pk/products/red-velvet-cake' },
  { no: 86, name: 'Layers Salted Caramel Cake', category: 'Cakes & Chocolates', price: 2999, status: 'Out of stock', image: 'https://flowerbouquet.pk/cdn/shop/files/Salted-Caramel-pgtfywoijtbli4rejl2zo5n85fjxtsgfc9iuvvghoo.jpg', link: 'https://flowerbouquet.pk/products/salted-caramel-cake' },
  { no: 87, name: 'Layers German Fudge Cake', category: 'Cakes & Chocolates', price: 2599, status: 'Out of stock', image: 'https://flowerbouquet.pk/cdn/shop/files/German-Fudge-pgtfyq3n7z2l8v0ym08lopazzqgdbwqazcygixq8w8.jpg', link: 'https://flowerbouquet.pk/products/german-fudge-cake' },
  { no: 88, name: 'Layers Chocolate Mousse Cake', category: 'Cakes & Chocolates', price: 2599, status: 'Out of stock', image: 'https://flowerbouquet.pk/cdn/shop/files/Chocolate-Mousse-pgtfz5529bn6emf466qmslidhwe8r2e0dfe87d3y4o.jpg', link: 'https://flowerbouquet.pk/products/chocolate-mousse-cake' },
  { no: 89, name: 'Layers Coffee Cake', category: 'Cakes & Chocolates', price: 2699, status: 'Out of stock', image: 'https://flowerbouquet.pk/cdn/shop/files/Coffee-pgtfyr1het3vkgzlgin8972gl4bqjlu1bhly07ouq0.jpg', link: 'https://flowerbouquet.pk/products/coffee-cake' },
  { no: 90, name: 'Decadent Delight', category: 'Gifts', price: 5999, status: 'In stock', image: 'https://flowerbouquet.pk/cdn/shop/files/14.png', link: 'https://flowerbouquet.pk/products/decadent-delight' },
  { no: 91, name: 'Sunflower Delight Bouquet', category: 'Gifts', price: 3499, status: 'In stock', image: 'https://flowerbouquet.pk/cdn/shop/files/sunflowers_trio_bouquet.png', link: 'https://flowerbouquet.pk/products/sunflower-delight-bouquet' },
  { no: 92, name: 'Radiant Floral Arrangement', category: 'Gifts', price: 6999, status: 'In stock', image: 'https://flowerbouquet.pk/cdn/shop/files/Radiant_Floral_Arrangement.png', link: 'https://flowerbouquet.pk/products/radiant-floral-arrangement' },
  { no: 93, name: 'Eternal Love', category: 'Gifts', price: 6999, status: 'In stock', image: 'https://flowerbouquet.pk/cdn/shop/files/469_24970e40-d7fb-41c4-a2ac-a2ff53a197f4.png', link: 'https://flowerbouquet.pk/products/eternal-love' },
  { no: 94, name: 'Enchanted Pink Rose Bouquet', category: 'Gifts', price: 7499, status: 'In stock', image: 'https://flowerbouquet.pk/cdn/shop/files/489.png', link: 'https://flowerbouquet.pk/products/enchanted-pink-rose-bouquet' },
  { no: 95, name: 'Polaroid bouquet', category: 'Gifts', price: 3999, status: 'Out of stock', image: 'https://flowerbouquet.pk/cdn/shop/files/Nostalgic_Polaroid_Memories.jpg', link: 'https://flowerbouquet.pk/products/polaroid-bouquet' },
  { no: 96, name: 'Decadent Donut Bouquet', category: 'Gifts', price: 6999, status: 'Out of stock', image: 'https://flowerbouquet.pk/cdn/shop/files/Decadent_Donut_Bouquet.jpg', link: 'https://flowerbouquet.pk/products/decadent-donut-bouquet' },
  { no: 97, name: 'White Elegance Bouquet', category: 'Gifts', price: 8499, status: 'Out of stock', image: 'https://flowerbouquet.pk/cdn/shop/files/171472211815-Photoroom.jpg', link: 'https://flowerbouquet.pk/products/white-elegance-bouquet' },
  { no: 98, name: 'Mercedes Car Flower Decoration', category: 'Gifts', price: 21999, status: 'Out of stock', image: 'https://flowerbouquet.pk/cdn/shop/files/Elegant_Pink_Flower_Car_Decoration.jpg', link: 'https://flowerbouquet.pk/products/elegant-pink-flower-car-decoration' },
  { no: 99, name: 'Pink Whisper Bouquet', category: 'Gifts', price: 4999, status: 'In stock', image: 'https://flowerbouquet.pk/cdn/shop/files/476_e8f7f55f-d513-437e-bc8d-b7a85bcb05ff.png', link: 'https://flowerbouquet.pk/products/pink-whisper-bouquet' },
  { no: 100, name: 'Beautiful Hairy Teddy', category: 'Gifts', price: 14500, status: 'Out of stock', image: 'https://flowerbouquet.pk/cdn/shop/files/teddy.jpg', link: 'https://flowerbouquet.pk/products/beautiful-hairy-teddy' },
];

// 3. 40 Real Pakistani Decoration Shop & Tent House Rental Equipment Catalog
export const PAKISTAN_DECORATION_RENTAL_ITEMS = [
  {
    name: 'Chiavari Gold Luxury Banquet Chairs (Set of 10)',
    category: 'Stage décor',
    rentalCategory: 'Stage décor',
    rentalPrice: 3500,
    hourlyRate: 600,
    depositAmount: 1500,
    description: 'Classic Chiavari gold-finished banquet chairs with plush ivory padded seat cushions. Essential for wedding stages, VIP guest seating, and royal banquet halls across Pakistan.',
    image: 'https://images.unsplash.com/photo-1519741497674-611481863552?q=80&w=1200&auto=format&fit=crop',
    dimensions: '36in (H) x 16in (W) x 16in (D) per Chair',
    material: 'Commercial Grade Gilded Steel Frame & Leatherette Cushion',
    status: 'In stock',
    totalQty: 25,
    isFeatured: true,
  },
  {
    name: 'Ghost Ultra-Clear Acrylic Modern Banquet Chairs (Set of 10)',
    category: 'Stage décor',
    rentalCategory: 'Stage décor',
    rentalPrice: 4500,
    hourlyRate: 800,
    depositAmount: 2000,
    description: 'Sleek transparent ghost chairs crafted from ultra-clear virgin polycarbonate. Perfect for modern Walima stages, white-themed receptions, and high-society dining setups in Lahore & Karachi.',
    image: 'https://images.unsplash.com/photo-1511795409834-ef04bbd61622?q=80&w=1200&auto=format&fit=crop',
    dimensions: '38in (H) x 15in (W) x 18in (D) per Chair',
    material: 'Virgin High-Density Acrylic Polycarbonate',
    status: 'In stock',
    totalQty: 20,
    isFeatured: true,
  },
  {
    name: 'Maharaja Royal Bride & Groom Carved Stage Throne Set (King & Queen)',
    category: 'Stage décor',
    rentalCategory: 'Stage décor',
    rentalPrice: 25000,
    hourlyRate: 4000,
    depositAmount: 8000,
    description: 'Grand hand-carved solid teakwood royal thrones featuring gold leaf foil finishing, deep diamond tufting, and regal crimson velvet upholstery for Barat & Walima bridal stages.',
    image: 'https://flowerbouquet.pk/cdn/shop/files/7717ce07c2d4c1c90fec292883f1738b.jpg?v=1721887354&width=533',
    dimensions: '68in (H) x 34in (W) x 30in (D) Dual Throne Suite',
    material: 'Hand-Carved Solid Sheesham/Teak Wood, 24K Gilded Leaf & Royal Red Velvet',
    status: 'In stock',
    totalQty: 6,
    isFeatured: true,
  },
  {
    name: 'Louis XVI Champagne Velvet Royal Armchairs (Pair of 2)',
    category: 'Stage décor',
    rentalCategory: 'Stage décor',
    rentalPrice: 7500,
    hourlyRate: 1200,
    depositAmount: 3000,
    description: 'French baroque-style champagne velvet armchairs with intricate gilded frame borders. Ideal for VIP head tables, Nikkah signings, and parent stage seating.',
    image: 'https://images.unsplash.com/photo-1583939003579-730e3918a45a?q=80&w=1200&auto=format&fit=crop',
    dimensions: '40in (H) x 26in (W) x 24in (D) Pair',
    material: 'Champagne Crushed Velvet, Carved Beechwood Frame & High-Resilience Foam',
    status: 'In stock',
    totalQty: 8,
    isFeatured: false,
  },
  {
    name: 'Chesterfield 3-Seater Tufted Velvet VIP Sofa (Ivory/Emerald)',
    category: 'Stage décor',
    rentalCategory: 'Stage décor',
    rentalPrice: 12000,
    hourlyRate: 1800,
    depositAmount: 4000,
    description: 'Luxury deep button-tufted Chesterfield 3-seater sofa with rolled arms. Gives an opulent look to Mehndi lounges, VIP enclosures, and bridal suites.',
    image: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?q=80&w=1200&auto=format&fit=crop',
    dimensions: '84in (L) x 36in (D) x 31in (H)',
    material: 'Heavyweight Velvet Upholstery & Solid Hardwood Internal Frame',
    status: 'In stock',
    totalQty: 10,
    isFeatured: true,
  },
  {
    name: 'Traditional Mehndi Low Floor Baithak Seating Set (Gaddi & Gao-Takia)',
    category: 'Stage décor',
    rentalCategory: 'Stage décor',
    rentalPrice: 8500,
    hourlyRate: 1400,
    depositAmount: 3000,
    description: 'Complete authentic Pakistani Mehndi baithak setup including 2 double floor mattresses (gaddis) with saffron/red velvet covers, 6 embroidered round bolsters (masnad/gao-takia), and 8 velvet throw cushions.',
    image: 'https://flowerbouquet.pk/cdn/shop/files/images_4.jpg?v=1720001562&width=533',
    dimensions: '12ft x 8ft Floor Area Setup',
    material: 'High-Density Foam Mattresses, Zari-Embroidered Velvet Bolsters & Cotton Lining',
    status: 'In stock',
    totalQty: 12,
    isFeatured: true,
  },
  {
    name: 'Hand-Carved Sheesham Wood Traditional Mehndi Swing (Jhoola)',
    category: 'Decorative props',
    rentalCategory: 'Decorative props',
    rentalPrice: 22000,
    hourlyRate: 3500,
    depositAmount: 7000,
    description: 'Authentic solid Sheesham wood Mehndi swing (Jhoola) featuring hand-carved floral jali work, heavy solid brass hanging chains, and comfortable velvet seat padding.',
    image: 'https://flowerbouquet.pk/cdn/shop/files/Majestic_Mehndi_Swing_Setup_with_Elegant_Drapes.jpg?v=1737027276&width=533',
    dimensions: '8ft (W) x 7.5ft (H) Rig Frame with 5ft Swing Seat',
    material: 'Seasoned Solid Sheesham Wood, Pure Cast Brass Hanging Hardware & Saffron Velvet',
    status: 'In stock',
    totalQty: 5,
    isFeatured: true,
  },
  {
    name: 'Modern Gilded Halo Floral Ring Hanging Swing',
    category: 'Decorative props',
    rentalCategory: 'Decorative props',
    rentalPrice: 18000,
    hourlyRate: 2800,
    depositAmount: 6000,
    description: 'Contemporary golden circular ring swing engineered for bridal stage photo corners, Mehndi entrances, and floral arch photography.',
    image: 'https://flowerbouquet.pk/cdn/shop/files/Outdoor_Floral_Mehndi_Swing_Setup.jpg?v=1737028997&width=533',
    dimensions: '7ft Diameter Halo Frame',
    material: 'Dual-Ring Tubular Steel with Brass Electroplating & Velvet Seat Ring',
    status: 'In stock',
    totalQty: 6,
    isFeatured: false,
  },
  {
    name: '6-8 Seater Round Banquet Dining Tables with Gold Jacquard Covers (Set of 4)',
    category: 'Stage décor',
    rentalCategory: 'Stage décor',
    rentalPrice: 6000,
    hourlyRate: 1000,
    depositAmount: 2000,
    description: 'Heavy-duty 6ft round banquet dining tables equipped with folding locking metal legs, thick plywood tops, and premium gold jacquard floor-length tablecloths.',
    image: 'https://images.unsplash.com/photo-1533090161767-e6ffed986c88?q=80&w=1200&auto=format&fit=crop',
    dimensions: '72in Diameter Round Table (Seats 8-10 Guests each)',
    material: 'Commercial 18mm Marine Plywood & Heavy Steel Wishbone Legs',
    status: 'In stock',
    totalQty: 15,
    isFeatured: false,
  },
  {
    name: '8ft Mirrored Presidential VIP Dining Top Table',
    category: 'Stage décor',
    rentalCategory: 'Stage décor',
    rentalPrice: 8500,
    hourlyRate: 1400,
    depositAmount: 3000,
    description: 'Beveled glass mirror-top presidential dining table on polished gold legs. Adds an ultra-luxurious reflective look for family and VIP head tables.',
    image: 'https://images.unsplash.com/photo-1527529482837-4698179dc6ce?q=80&w=1200&auto=format&fit=crop',
    dimensions: '8ft (L) x 40in (W) x 30in (H)',
    material: '8mm Beveled Safety Mirror Glass & Gold Stainless Steel Truss Base',
    status: 'In stock',
    totalQty: 8,
    isFeatured: true,
  },
  {
    name: 'Lucite Translucent LED Glow Cocktail Highboy Tables (Set of 4)',
    category: 'Stage décor',
    rentalCategory: 'Stage décor',
    rentalPrice: 7500,
    hourlyRate: 1200,
    depositAmount: 2500,
    description: 'Translucent acrylic high cocktail tables with built-in multi-color wireless LED glow illumination. Perfect for mocktail stations and reception welcome areas.',
    image: 'https://images.unsplash.com/photo-1530103862676-de8c9debad1d?q=80&w=1200&auto=format&fit=crop',
    dimensions: '42in (H) x 24in (Diameter) Round Tops',
    material: 'Heavy Gauge Optical Acrylic with RGB Rechargeable LED Base',
    status: 'In stock',
    totalQty: 8,
    isFeatured: false,
  },
  {
    name: 'Traditional Hand-Painted Wooden Mehndi Chowkis (Set of 6)',
    category: 'Decorative props',
    rentalCategory: 'Decorative props',
    rentalPrice: 3500,
    hourlyRate: 600,
    depositAmount: 1500,
    description: 'Traditional low wooden chowki tables painted with truck-art and floral motifs for placing Mehndi thaalis, mithai boxes, and oil bowls.',
    image: 'https://flowerbouquet.pk/cdn/shop/files/Elegant_Outdoor_Mehndi_Pavilion_with_Floor_Seating.jpg?v=1737029691&width=533',
    dimensions: '18in x 18in x 8in (H) per Chowki',
    material: 'Solid Wood with Hand-Painted Enamel & Gota Borders',
    status: 'In stock',
    totalQty: 10,
    isFeatured: false,
  },
  {
    name: 'Gold Circular Halo Floral Ring Moon Gate Arch (8ft Diameter)',
    category: 'Arches',
    rentalCategory: 'Arches',
    rentalPrice: 15000,
    hourlyRate: 2500,
    depositAmount: 5000,
    description: 'Heavy-duty double ring golden metal arch frame with weighted anti-tip base plates and floral grid mounting clips. The gold standard for wedding stage arches.',
    image: 'https://flowerbouquet.pk/cdn/shop/files/Modern_Mehndi_Backdrop_with_Circular_Floral_Design.jpg?v=1737028867&width=533',
    dimensions: '8ft (H) x 8ft (W) Circular Gate',
    material: 'Titanium Gold Electroplated Steel Tube Arch',
    status: 'In stock',
    totalQty: 8,
    isFeatured: true,
  },
  {
    name: 'Geometric Hexagonal Wooden Wedding Archway (8.5ft)',
    category: 'Arches',
    rentalCategory: 'Arches',
    rentalPrice: 12000,
    hourlyRate: 2000,
    depositAmount: 4000,
    description: 'Solid pine timber hexagon arch frame for boho-chic Nikkah ceremonies, outdoor garden weddings, and photo entrance gates.',
    image: 'https://flowerbouquet.pk/cdn/shop/files/Rustic_Mehndi_Corner_with_Floral_Arch_and_Tassels.jpg?v=1737029091&width=533',
    dimensions: '8.5ft (H) x 8.5ft (W)',
    material: 'Stained Natural Pine Wood with Heavy Metal Corner Brackets',
    status: 'In stock',
    totalQty: 6,
    isFeatured: false,
  },
  {
    name: 'Shimmer Sequin Wall Photobooth Backdrop (8ft x 8ft Champagne Gold)',
    category: 'Backdrops',
    rentalCategory: 'Backdrops',
    rentalPrice: 14000,
    hourlyRate: 2200,
    depositAmount: 4500,
    description: 'Reflective wind-activated metallic sequin tile wall on aluminum frame. Creates a sparkling glamorous photobooth backdrop for wedding receptions and galas.',
    image: 'https://images.unsplash.com/photo-1530103862676-de8c9debad1d?q=80&w=1200&auto=format&fit=crop',
    dimensions: '8ft (W) x 8ft (H) Wall Panel',
    material: 'Reflective Polycarbonate Mirror Sequins on Telescopic Aluminum Grid',
    status: 'In stock',
    totalQty: 8,
    isFeatured: true,
  },
  {
    name: 'Royal Velvet Stage Drapes & Pipe-and-Drape Frame (20ft x 12ft)',
    category: 'Backdrops',
    rentalCategory: 'Backdrops',
    rentalPrice: 16000,
    hourlyRate: 2500,
    depositAmount: 5000,
    description: 'Heavyweight flame-retardant velvet drape curtain panels (available in Deep Crimson, Royal Gold, Emerald, and Midnight Black) with heavy duty uprights and crossbars.',
    image: 'https://flowerbouquet.pk/cdn/shop/files/Luxurious_Indoor_Mehndi_Setup_with_Red_Floral_Arch.jpg?v=1737029310&width=533',
    dimensions: '20ft (W) x 12ft (H) Expandable Stage Backdrop',
    material: 'Triple-Weave Heavyweight Velvet Fabric & Telescopic Aluminum Pipes',
    status: 'In stock',
    totalQty: 10,
    isFeatured: false,
  },
  {
    name: 'Heavy-Duty Aluminum Box Truss Stage Rig (30ft x 14ft)',
    category: 'Stage décor',
    rentalCategory: 'Stage décor',
    rentalPrice: 35000,
    hourlyRate: 5000,
    depositAmount: 10000,
    description: 'Certified 290mm aluminum box truss framework with heavy steel baseplates for hanging massive floral installations, moving head lights, and crystal chandeliers over stages.',
    image: 'https://flowerbouquet.pk/cdn/shop/files/weddingstage.jpg?v=1716522682&width=533',
    dimensions: '30ft Span x 14ft Height Goalpost / Box Configuration',
    material: 'T6-6082 Aircraft Grade Aluminum Truss Rigging',
    status: 'In stock',
    totalQty: 4,
    isFeatured: true,
  },
  {
    name: '4ft Multi-Tier K9 Optical Crystal Waterfall Chandelier',
    category: 'Lighting',
    rentalCategory: 'Lighting',
    rentalPrice: 12500,
    hourlyRate: 2000,
    depositAmount: 4000,
    description: 'Imperial 4-tier faceted crystal glass chandelier with internal warm gold LED lighting. Suspended over bridal walkways or stage canopies for royal grandeur.',
    image: 'https://flowerbouquet.pk/cdn/shop/files/walima_decoration.png?v=1726123619&width=533',
    dimensions: '48in (H) x 32in (Diameter) Chandelier Tier',
    material: 'K9 Optical Crystal Drops, Chrome/Gold Plated Steel Ring Truss',
    status: 'In stock',
    totalQty: 8,
    isFeatured: true,
  },
  {
    name: '5-Arm Optical Crystal & Gilded Brass Candelabras (Set of 6)',
    category: 'Lighting',
    rentalCategory: 'Lighting',
    rentalPrice: 7500,
    hourlyRate: 1200,
    depositAmount: 2500,
    description: 'Magnificent 5-arm crystal candelabras with glass hurricane globes for banquet guest tables, dinner pathways, and stage edge decor.',
    image: 'https://images.unsplash.com/photo-1469371670807-013ccf25f16a?q=80&w=1200&auto=format&fit=crop',
    dimensions: '32in (H) x 18in (Spread) per Candelabra',
    material: 'Cut Crystal Glass Stems & Hurricane Globes with Heavy Brass Weighted Base',
    status: 'In stock',
    totalQty: 12,
    isFeatured: false,
  },
  {
    name: '40ft Suspended Fairy Light Mesh Canopy & Entrance Tunnel',
    category: 'Lighting',
    rentalCategory: 'Lighting',
    rentalPrice: 18000,
    hourlyRate: 2800,
    depositAmount: 6000,
    description: 'Dense micro warm-white LED fairy light curtain netting for wedding walkway tunnels, marquee ceilings, and farmhouse lawn tree wraps.',
    image: 'https://flowerbouquet.pk/cdn/shop/files/Twinkling_Mehndi_Backdrop_with_Fairy_Lights_and_Greenery.jpg?v=1737028502&width=533',
    dimensions: '40ft (L) x 12ft (W) Light Canopy Span',
    material: 'Weatherproof Commercial Grade Copper Wire Fairy LEDs (Over 4,000 diodes)',
    status: 'In stock',
    totalQty: 10,
    isFeatured: true,
  },
  {
    name: 'DMX Stage RGBW LED Uplighting & Wash PAR Cans (Set of 8)',
    category: 'Lighting',
    rentalCategory: 'Lighting',
    rentalPrice: 10000,
    hourlyRate: 1500,
    depositAmount: 3000,
    description: 'High-power 18x12W RGBW LED stage par cans with DMX512 controller and linking cables. Provides cinematic wall washes in amber, gold, violet, and magenta.',
    image: 'https://flowerbouquet.pk/cdn/shop/files/7717ce07c2d4c1c90fec292883f1738b.jpg?v=1721887354&width=533',
    dimensions: '8 Fixtures with Power & Signal Cabling + Master Controller',
    material: 'Cast Aluminum Housing with High-Intensity Quad-Color LEDs',
    status: 'In stock',
    totalQty: 10,
    isFeatured: false,
  },
  {
    name: 'Antique Pierced Moroccan Brass Floor Lanterns (Set of 6)',
    category: 'Lighting',
    rentalCategory: 'Lighting',
    rentalPrice: 6500,
    hourlyRate: 1000,
    depositAmount: 2000,
    description: 'Authentic pierced brass Moroccan floor lanterns featuring intricate Islamic geometric latticework. Complete with battery-powered flicker pillar candles.',
    image: 'https://flowerbouquet.pk/cdn/shop/files/Vibrant_Floral_Mehndi_Stage_with_Traditional_Se.jpg?v=1737027082&width=533',
    dimensions: 'Heights Ranging from 20in to 36in Tall (Assorted Set of 6)',
    material: 'Hand-Etched Spun Solid Brass with Antique Patina',
    status: 'In stock',
    totalQty: 12,
    isFeatured: true,
  },
  {
    name: 'Vintage Edison Bulb Drop Chandeliers & Festoon String (Set of 4 Clusters)',
    category: 'Lighting',
    rentalCategory: 'Lighting',
    rentalPrice: 8500,
    hourlyRate: 1300,
    depositAmount: 2500,
    description: 'Suspended warm Edison carbon-filament bulbs hanging from natural jute ropes or black cords with dimming control for rustic open-air wedding dinners.',
    image: 'https://images.unsplash.com/photo-1507676184212-d03ab07a01bf?q=80&w=1200&auto=format&fit=crop',
    dimensions: '4 Drop Clusters with 24 Total Bulbs',
    material: 'Amber Tinted Glass Edison Bulbs, Jute Ropes & Dimmer Console',
    status: 'In stock',
    totalQty: 8,
    isFeatured: false,
  },
  {
    name: 'Wedding LED Neon Flex Signs ("Better Together" & "Happily Ever After")',
    category: 'Lighting',
    rentalCategory: 'Lighting',
    rentalPrice: 4500,
    hourlyRate: 700,
    depositAmount: 1500,
    description: 'Warm white ultra-bright LED neon flex script signs on clear acrylic backboards with hanging chains and dimmer adapter. Perfect for grass walls & flower backdrops.',
    image: 'https://images.unsplash.com/photo-1527529482837-4698179dc6ce?q=80&w=1200&auto=format&fit=crop',
    dimensions: '40in x 20in Sign Board',
    material: 'Silicone Neon Flex Tubing on 6mm Cast Acrylic',
    status: 'In stock',
    totalQty: 10,
    isFeatured: false,
  },
  {
    name: 'Cold Spark Fireworks Pyro Fountain Machines (Pair of 2)',
    category: 'Lighting',
    rentalCategory: 'Lighting',
    rentalPrice: 16000,
    hourlyRate: 2500,
    depositAmount: 5000,
    description: 'Safe non-hazardous cold spark fountain machines with DMX remote triggers and composite titanium powder for grand bridal stage entrances and cake cutting moments.',
    image: 'https://images.unsplash.com/photo-1464366400600-7168b8af9bc3?q=80&w=1200&auto=format&fit=crop',
    dimensions: 'Pair of 2 Spark Units (Spark Height 2m - 4m Adjustable)',
    material: 'Die-Cast Metal Machine Housing with Wireless RF Remote',
    status: 'In stock',
    totalQty: 6,
    isFeatured: true,
  },
  {
    name: 'High-Gloss White Acrylic Mirror Stage Deck Flooring (24ft x 12ft)',
    category: 'Stage décor',
    rentalCategory: 'Stage décor',
    rentalPrice: 28000,
    hourlyRate: 4500,
    depositAmount: 9000,
    description: 'Seamless high-gloss mirror-finish white acrylic stage floor panels with protective peel-off film. Gives the ballroom stage an immaculate couture look.',
    image: 'https://flowerbouquet.pk/cdn/shop/files/walima_decoration.png?v=1726123619&width=533',
    dimensions: '24ft (W) x 12ft (D) Stage Deck Surface',
    material: '3mm High-Gloss White Acrylic Sheet with Interlocking Subfloor',
    status: 'In stock',
    totalQty: 5,
    isFeatured: true,
  },
  {
    name: 'Royal Red Velvet Bridal Entrance Aisle Carpet (50ft x 6ft)',
    category: 'Stage décor',
    rentalCategory: 'Stage décor',
    rentalPrice: 6500,
    hourlyRate: 1000,
    depositAmount: 2000,
    description: 'Plush royal red velvet wedding walkway carpet with taped seams and heavy brass threshold binders for grand bridal entry aisles.',
    image: 'https://images.unsplash.com/photo-1583939003579-730e3918a45a?q=80&w=1200&auto=format&fit=crop',
    dimensions: '50ft (L) x 6ft (W) Walkway Runner',
    material: 'Heavy Dense Pile Velvet Carpet with Rubberized Anti-Slip Backing',
    status: 'In stock',
    totalQty: 8,
    isFeatured: false,
  },
  {
    name: 'Portable Heavy-Duty Aluminum Interlocking Staging Risers (24ft x 16ft)',
    category: 'Stage décor',
    rentalCategory: 'Stage décor',
    rentalPrice: 24000,
    hourlyRate: 3800,
    depositAmount: 8000,
    description: 'Industrial modular portable stage platform risers (elevated 2ft) with non-skid carpeted surface and skirting for live wedding performances and bridal stages.',
    image: 'https://flowerbouquet.pk/cdn/shop/files/weddingstage.jpg?v=1716522682&width=533',
    dimensions: '24ft x 16ft Modular Deck (Configurable)',
    material: 'Aluminum Alloy Frame with 18mm Anti-Skid Plywood Tops',
    status: 'In stock',
    totalQty: 4,
    isFeatured: false,
  },
  {
    name: 'Handcrafted Rajasthani Embroidered Umbrellas / Chhatris (Set of 8)',
    category: 'Decorative props',
    rentalCategory: 'Decorative props',
    rentalPrice: 4500,
    hourlyRate: 700,
    depositAmount: 1500,
    description: 'Colorful Rajasthani handicraft umbrellas with mirror embroidery, dangling thread tassels, and brass floor stands for traditional Mehndi decor.',
    image: 'https://flowerbouquet.pk/cdn/shop/files/Festive_Umbrella-Themed_Mehndi_Backdrop.jpg?v=1737028135&width=533',
    dimensions: '28in Canopy Diameter with 4ft Tall Floor Stands',
    material: 'Embroidered Cotton Canvas, Mirror Work & Bamboo Ribs with Steel Stands',
    status: 'In stock',
    totalQty: 10,
    isFeatured: true,
  },
  {
    name: 'Solid Spun Brass Urli Basins for Floating Flowers & Candles (Set of 4)',
    category: 'Decorative props',
    rentalCategory: 'Decorative props',
    rentalPrice: 5500,
    hourlyRate: 900,
    depositAmount: 2000,
    description: 'Traditional deep spun brass urlis with fluted rims for filling with scented rosewater, fresh floating marigolds, and glowing t-light candles at venue entrance foyers.',
    image: 'https://flowerbouquet.pk/cdn/shop/files/7717ce07c2d4c1c90fec292883f1738b.jpg?v=1721887354&width=533',
    dimensions: 'Assorted Diameters: 16in, 18in, 21in, and 24in Basins',
    material: 'Heavyweight Pure Spun Brass with Protective Lacquer',
    status: 'In stock',
    totalQty: 8,
    isFeatured: true,
  },
  {
    name: 'Decorated Traditional Pakistani Mehndi Dholaks & Dandiyas (Set of 2)',
    category: 'Decorative props',
    rentalCategory: 'Decorative props',
    rentalPrice: 3000,
    hourlyRate: 500,
    depositAmount: 1000,
    description: 'Authentic mango-wood dholaks dressed in yellow velvet and gota-kinari covers with matching wooden dandi sticks for lively Mehndi ladies singing and sangeet sessions.',
    image: 'https://flowerbouquet.pk/cdn/shop/files/images_4.jpg?v=1720001562&width=533',
    dimensions: 'Standard 18in Concert Dholak Pair',
    material: 'Seasoned Mango Wood, Goat Skin Heads & Gota Velvet Trimmings',
    status: 'In stock',
    totalQty: 8,
    isFeatured: false,
  },
  {
    name: 'Gilded Baroque Welcome Easel with Custom Mirrored / Acrylic Sign',
    category: 'Decorative props',
    rentalCategory: 'Decorative props',
    rentalPrice: 4500,
    hourlyRate: 700,
    depositAmount: 1500,
    description: 'Ornate carved gold artist easel stand with personalized mirror-finish welcome board and fresh baby breath floral hedge styling.',
    image: 'https://flowerbouquet.pk/cdn/shop/files/Enchanting_Staircase_Decor.jpg?v=1735215523&width=533',
    dimensions: '65in (H) Easel with 24in x 36in Welcome Sign',
    material: 'Solid Carved Wood in Gold Leaf with 5mm Acrylic Mirror Board',
    status: 'In stock',
    totalQty: 8,
    isFeatured: false,
  },
  {
    name: 'Geometric High-Rise Gold Floral Table Centerpiece Stands (Set of 10)',
    category: 'Decorative props',
    rentalCategory: 'Decorative props',
    rentalPrice: 7500,
    hourlyRate: 1200,
    depositAmount: 2500,
    description: 'Tall 3ft geometric golden rectangular prism columns for elevating fresh floral domes and cascading orchids above guest eye-level at dining tables.',
    image: 'https://images.unsplash.com/photo-1519741497674-611481863552?q=80&w=1200&auto=format&fit=crop',
    dimensions: '36in (H) x 10in (W) x 10in (D) Columns (Set of 10)',
    material: 'High-Gloss Electroplated Gilded Metal Frame',
    status: 'In stock',
    totalQty: 10,
    isFeatured: false,
  },
  {
    name: 'Stainless Steel Roll-Top Catering Chafing Dishes (Set of 6)',
    category: 'Decorative props',
    rentalCategory: 'Decorative props',
    rentalPrice: 6000,
    hourlyRate: 1000,
    depositAmount: 2000,
    description: 'Commercial mirror-polish stainless steel roll-top buffet food warmers (9-liter capacity) with water pans, food inserts, and dual fuel gel burners for wedding buffets.',
    image: 'https://images.unsplash.com/photo-1555244162-803834f70033?q=80&w=1200&auto=format&fit=crop',
    dimensions: 'Full Size 9L Chafers (Set of 6 Units)',
    material: 'Food Grade 18/10 Stainless Steel with 90°/180° Roll-Top Dome Lid',
    status: 'In stock',
    totalQty: 12,
    isFeatured: true,
  },
  {
    name: 'Deluxe Gold-Rimmed Bone China Dinnerware & Silver Cutlery (Set for 100 Guests)',
    category: 'Decorative props',
    rentalCategory: 'Decorative props',
    rentalPrice: 15000,
    hourlyRate: 2500,
    depositAmount: 5000,
    description: 'Complete VIP banquet tableware setup for 100 guests: 10.5in gold-rimmed dinner plates, side plates, dessert bowls, crystal water goblets, and heavy stainless cutlery.',
    image: 'https://images.unsplash.com/photo-1578474846511-04ba529f0b88?q=80&w=1200&auto=format&fit=crop',
    dimensions: '100 Guest 5-Piece Place Settings (500 Total Pieces)',
    material: 'Fine Bone China Porcelain with 24K Gold Decal Rim & 18/10 Stainless Cutlery',
    status: 'In stock',
    totalQty: 6,
    isFeatured: false,
  },
  {
    name: 'Traditional Mughal Brass Deg & Royal Serving Warmers (Set of 4)',
    category: 'Decorative props',
    rentalCategory: 'Decorative props',
    rentalPrice: 7000,
    hourlyRate: 1100,
    depositAmount: 2500,
    description: 'Authentic Mughal-style tin-lined brass serving deags with ornate domed lids and brass serving ladles for presenting biryani and korma at royal banquets.',
    image: 'https://flowerbouquet.pk/cdn/shop/files/7717ce07c2d4c1c90fec292883f1738b.jpg?v=1721887354&width=533',
    dimensions: 'Medium & Large Sized Deags (Set of 4 with Brass Stands)',
    material: 'Pure Hand-Hammered Brass with Interior Food-Safe Tin Plating (Qalai)',
    status: 'In stock',
    totalQty: 8,
    isFeatured: false,
  },
  {
    name: 'Traditional Saffron & Emerald Mehndi Shamiana Marquee Canopy (30ft x 30ft)',
    category: 'Backdrops',
    rentalCategory: 'Backdrops',
    rentalPrice: 22000,
    hourlyRate: 3500,
    depositAmount: 7000,
    description: 'Traditional Pakistani Mehndi shamiana tent canopy crafted with waterproof canvas ceiling, yellow/green scalloped valence trims, and sturdy steel center poles.',
    image: 'https://flowerbouquet.pk/cdn/shop/files/309.jpg?v=1737027404&width=533',
    dimensions: '30ft x 30ft Covered Lawn Enclosure (Seats up to 120 Guests)',
    material: 'Heavyweight Water-Repellent Cotton Canvas & Steel Tubular Poles',
    status: 'In stock',
    totalQty: 5,
    isFeatured: true,
  },
  {
    name: 'White High-Peak German Pagoda Canopy Marquee Tent (20ft x 20ft)',
    category: 'Backdrops',
    rentalCategory: 'Backdrops',
    rentalPrice: 18000,
    hourlyRate: 2800,
    depositAmount: 6000,
    description: 'Elegant white high-peak tensile pagoda tent with aluminum framework and optional clear window sidewalls for VIP entrance foyers and outdoor dining.',
    image: 'https://flowerbouquet.pk/cdn/shop/files/weddingstage.jpg?v=1716522682&width=533',
    dimensions: '20ft x 20ft Pagoda Structure (400 sq ft Area)',
    material: 'Anodized Aluminum Frame & 850g/sqm Fire-Retardant White PVC Fabric',
    status: 'In stock',
    totalQty: 6,
    isFeatured: false,
  },
];

